musicPlayTime: 30
choseTime: 15
roundLimit: 5

reward:
  snowballs:
    correct: 10
  vault:
    enabled: false
    correct: 10
    wrong: 5
  command:
    enabled: true
    correct:
      - "snowballs add %playerName% %snowballs%"
    wrong:
      -

languages:
  default: "en_us"
  languages:
    - en_us
    - de_de

bungeecord:
  enable: false
  lobby: Lobby

database:
  enable: false
  host: "127.0.0.1"
  port: 3306
  database: "WhatsTheSongsName"
  username: "root"
  password: "iMsooo1SavePassword"
